name: Twitter-Server CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Yarn
      run: npm install -g yarn
    - run: yarn install
      working-directory: ./twitter-server
    - run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
      working-directory: ./twitter-server
    - run: yarn build
      working-directory: ./twitter-server
