name: Twitter-Server CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: ./twitter-server/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/twitter-server/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: npm install -g yarn
    - run: yarn install
      working-directory: ./twitter-server
    - run: |
        touch ./twitter-server/.env
        echo "${{ secrets.PROD_ENV_FILE }}" > ./twitter-server/.env
    - run: npm run build
      working-directory: ./twitter-server
